kizniche/Mycodo

- 3.5/cgi-bin/mycodo.py
- 3.5/includes/mycodo.php
- 3.5/includes/restricted.php
- 3.5/update-database.py
Fix DS18B20 support, fix relay image button switch, fix PID support DB18B20, fix addition relays.
> Fix DS18B20 support, same fix relay

- 3.5/cgi-bin/mycodo.py
More cleaning.  This was semi-automated so their shouldn't be any typos but you should run it on your system to make sure
> Sql cleanup

- 3.5/cgi-bin/mycodo.py
As always this might need to be double checked
> Rename 'sensor' to 'sensor_id'

- 3.5/mycodo_core/mycodo.py
Reverting back to the stable version, and having now the LCD panel, I caught this mix-up
> DHT sensor temperature and humidity reading is switched on the LCD

- mycodo/inputs/bmp280.py
Hi Kyle,  I tested these changes with the 6.2.3 release locally.   I usually use the BME280 variant so I hadn't noticed this one going south somewhere along the way.  The changes are simple and mostly mirror what Vitally has in his repo.  So this one was rather easy as they go and I seem to be in a persistent code-writing mood.
> Proposed fixes for #522 BMP280.py module (Python3 compat)

- mycodo/mycodo_flask/templates/pages/info.html
I feel almost silly even opening a PR for that. But it just caught my eye ;-)
> Fix typo in info template

- mycodo/mycodo_flask/translations/nl/LC_MESSAGES/messages.po
These are cringeworthy on the main menu
> Update dutch translations

- mycodo-manual.rst
> Update Mycodo Manual.rst

- mycodo/inputs/MLX90614.py
Feel free to make edits. As mentioned previously, the two temperature measurements are not differently labeled.
> Adding MLX90614 sensor input

- mycodo/inputs/anyleaf_orp.py
- mycodo/inputs/anyleaf_ph.py
This doesn't change any functionality; it's an improvement to documentation based on feedback.
> Improved instructions for AnyLeaf calibration

- mycodo/functions/function_pid_autotune.py
> Fixed can't select channel 0

- mycodo/mycodo_flask/static/css/custom.css
- mycodo/widgets/widget_graph_synchronous.py
This should correct the title issues that cropped up in the synchronous graph widget.
Desktop:
Tablet:
> fix: correct title/button issue on synchronous graph widget

- mycodo/inputs/ina219x.py
Allow users to calibrate the bus voltage range for INA219x sensor devices (16V / 32V).
> feature: add bus voltage range to INA219x sensor input

- mycodo/mycodo_flask/templates/layout.html
I've not been able to see the *hamburger* icon on the navbar menu when viewing on mobile. This change addresses that.
I've also added a bit of margin to the bottom of the navbar when Mycodo is viewed on mobile devices.
> Font Awesome for nav menu, add margin to bottom of nav menu

- mycodo/config.py
- mycodo/controllers/controller_lcd.py
- mycodo/devices/lcd_grove_lcd_rgb.py
- mycodo/mycodo_flask/templates/pages/lcd.html
- mycodo/mycodo_flask/utils/utils_lcd.py
This PR adds the Grove LCD RGB Backlight as a device.
https://wiki.seeedstudio.com/Grove-LCD_RGB_Backlight/
> Add Grove RGB LCD

- mycodo/controllers/controller_lcd.py
- mycodo/devices/lcd_grove_lcd_rgb.py
- mycodo/mycodo_client.py
- mycodo/mycodo_daemon.py
- mycodo/mycodo_flask/utils/utils_lcd.py
- mycodo/utils/function_actions.py
- Gets rid of the dependency on the Grove python library
- Wires up the actions for the backlight color changes
> Fix Grove LCD RGB Backlight

- mycodo/inputs/rpi_edge.py
- mycodo/inputs/rpi_gpio_state.py
Added option to configure input to use pull-up and pull-down. Not selected / Default remains floating.
https://kylegabriel.com/forum/general-discussion/rpi-gpio-pull-up-and-down/#post-1293
> Support pull-up and pull-down in RPI.GPIO (state and edge detect)

- mycodo/controllers/controller_trigger.py
- mycodo/mycodo_flask/utils/utils_trigger.py
- mycodo/outputs/pwm_pca9685.py
- mycodo/utils/method.py
Selecting the method did fail for a set of reasons. Please see review comments for details.
> Fixed issues in trigger_run_pwm_method

- .deepsource.toml
- mycodo/config.py
- mycodo/inputs/hdc1000.py
- mycodo/inputs/rpi_edge.py
- mycodo/mycodo_flask/routes_general.py
- mycodo/mycodo_flask/utils/utils_function.py
- mycodo/mycodo_flask/utils/utils_input.py
- mycodo/outputs/base_output.py
- mycodo/outputs/grove_multichannel_relay.py
- mycodo/outputs/pcf8574.py
- mycodo/tests/software_tests/test_factories.py
- mycodo/tests/software_tests/test_mycodo_flask/test_endpoints.py
- mycodo/utils/method.py
- mycodo/utils/psypy.py
- mycodo/utils/stats.py
Hi :wave:, I ran DeepSource analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/Mycodo/) to consider.
This PR fixes a few of the issues detected.
- Use literals instead of function calls to assign data structure.
- Simplify `if` statements.
- Remove reimported modules.
- Refactor assert statement from non-test files.
- Use `is` for comparison with True.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.
> Refactor code quality issues

- databases/alembic_post.py
- docker/Dockerfile
- docker/docker-compose.yml
- docker/setup.sh
- mycodo/mycodo_flask/routes_general.py
- mycodo/scripts/dependencies.sh
- mycodo/scripts/upgrade_commands.sh
- mycodo/utils/update_dependencies.py
- release-checklist.md
> fix docker setup

- mycodo/inputs/anyleaf_ec.py
- mycodo/inputs/anyleaf_orp.py
- mycodo/inputs/anyleaf_ph.py
Fixes https://github.com/kizniche/Mycodo/issues/1032
Also, upped Anyleaf dependency version.
> Anyleaf orp fix

- mycodo/inputs/mqtt_paho_json.py
I was lazy and reseted my forked master branch which closed PR#1044 and open a new PR here
> PR for #1043 : Introducing jmespath for finding values in complex JSON structures

- install/setup.sh
- mycodo/scripts/mycodo_wrapper.c
- mycodo/scripts/upgrade_commands.sh
A change which gives a clean installation log on a VM with fresh Ubuntu 20.04 amd64 server image. Basic features of the installed Mycodo system are also functional.
> Support installation on generic Ubuntu

- docs/Upgrade-Backup-Restore.md
> Link typo correction

- mycodo/utils/pid_controller_default.py
> keep pid enabled in band but force error to 0

- CHANGELOG.md
- docs/Supported-Inputs-By-Measurement.md
- docs/Supported-Inputs.md
- mycodo/inputs/mhz_14.py
Add support for the Winsen MH-Z14A CO2 sensor: https://www.winsen-sensor.com/sensors/co2-sensor/mh-z14a.html
The sensor has a neat auto-calibration feature, which is completely useless in closed environments that produce their own CO2 :(
I wasn't sure what coding style the project currently uses so you may want to reformat the code for consistency (currently formatted using Black).
> Add input: MH-Z14A CO2 sensor.

- mycodo/mycodo_flask/api/output.py
> volume api typo

- CHANGELOG.md
- mycodo/inputs/dht20.py
Add DHT20 Humidity/Temperature sensor used in e.g.https://www.seeedstudio.com/Grove-Temperature-Humidity-Sensor-V2-0-DHT20-p-4967.html.
I own this sensor and have tested it with my installation of Mycodo.
> Add DHT20 Humidity/Temperature Sensor

- mycodo/inputs/max31855_circuitpython.py
Add CircuitPython library support for MAX31855 input. Resolves #1391.
> Add input for MAX31855 using CircuitPython library
