- 3.5/cgi-bin/mycodo.py
This code is a test to see if you would be open to it.  I see a lot of conditionals that are difficult to understand because I am not familiar with the pin settings.  This particular function ```read_relay``` has two conditions that if either are true the relay is considered 'on'.   Rather than have the magic numbers in the conditional I am thinking that you could name these.   Something like 'relay_engaged_down' or 'relay_engaged_up'...  I am taking a wild guess here, that probably isn't what is happening.
If we can break some of the longer lines up into local variables I believe the code could be much easier to read.
> named conditionals 

- mycodo/mycodo_flask/general_routes.py
Simplify the admin check by removing the redundant db check since the flask factory builds the db files when it builds the UI.
> closes #140.  Removed redundant db check

- mycodo/mycodo_flask/templates/layout.html
this is the file that you need upload in /static/img/. this file is the icon that setting when adding to home the page live:
the results is this:
I've been led by https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
and
https://gist.github.com/irae/1042167
> Add tag for webapp osx

- mycodo/inputs/mh_z19.py
This is just a suggestion of a minimum to do - you will probably want to re-write it into the init or where it makes sense to catch the point of activating.  My assumption is that you never need to enable (probably wrong).  I think this may be programmed into the firmware and re-enabled with any reset, self initiated or external (power cycle, etc.) I'll bet lots of folks think they have a defective sensor after some time operating, assuming they ever question the data.
> Add method to disable ABC feature of B version sensor

- .travis.yml
Fix Travis CI build errors #3378-Present. PiGPIO installation methods regarding wget from abyz.com/... are no longer supported, change wget source and unzip procedure to reflect new install methods.
> Fix Travis build errors

- README.rst
Changed "proportional-derivative-integral" to "proportional-integral-derivative" (PID).
> Update README.rst - Correct `proportional-integral-derivative` in PID section

- mycodo/mycodo_flask/static/css/custom.css
- mycodo/mycodo_flask/templates/pages/dashboard.html
This proposed change removes much of the inline CSS styling on dashboard widgets and centers widget titles within their panels.
I've also knocked down the opacity on the settings cog icon unless the mouse is hovering over the icon or the link is active.
This change has been tested in Chrome, Firefox, Safari, and Opera without displaying any issues at various browser sizes. I also tested all themes to ensure that the change did not break any styling.
Dragging works along with the settings cog link.
I will note that there's still some inline CSS styling being added programmatically via this line:
```python
{% include 'user_templates/{}'.format(file_title_bar) %}
```
For instance, `padding-right` is being added to titles in this function. That inline style is no longer needed. I wasn't able …
> tweak: reworked widget title bar on dashboard widgets

- mycodo/config_devices_units.py
- mycodo/inputs/ina219x.py
- mycodo/tests/software_tests/test_inputs/test_inputs.py
This commit adds support for T.I. INA219x devices (e.g. INA219A, INA219B).
Current-reading is important for sensors that output current rather than voltage.
For instance, the Dwyer 2D4x series of CO2 sensors can output either voltage or current, with a variety of different supported current ranges (0-20mA,4-20mA,0-10mA,2-10mA).
In addition to the library, changes have been made to `config_devices_units.py` to add milliamp (mA) to the list of supported units.
> Added support for Texas Instruments INA219x current-reading sensors

- mycodo/mycodo_flask/static/css/custom.css
- mycodo/widgets/widget_indicator.py
Small change to horizontally and vertically center the indicator graphic within the indicator widget.
> tweak: center indicator graphic within indicator widget

- mycodo/config.py
This fix corrects the CircuitPython `framebuf` module dependency for SD1306 LCDs.
The correct dependency to install is `adafruit-circuitpython-framebuf`, not `Adafruit-Circuitpython-Framebuff`.
> Fix dependency name (framebuf) for CircuitPython SD1306 devices

- mycodo/inputs/ina219x.py
Hi, 
I'm using TCA9548A multiplexer so I need to set the specific i2c bus for INA219 sensor. I found that the current INA219 sensor module implementation doesn't take into account i2c bus selected in the configuration, but using the default board i2c instead. This PR fixes the problem using adafruit_extended_bus library (same as in other modules).
Thanks and keep up your GREAT work :+1:
> Fix INA219x sensor i2c bus initialization

- mycodo/inputs/adafruit_i2c_soil.py
It seems my main change on this sneaked in already with https://github.com/kizniche/Mycodo/pull/957
I was not aware that any changes I do in my fork after requesting a PR but before it is merged are automatically amended to the existing PR. Hope you also agree to have this device included.
This PR is just one little extension to allow the 4 different i2c addresses the sensor supports via solder jumpers. They are not documented so I tried all combinations with my device manually.
> Add support for adafruit i2c capacitive soil moisture sensor

- mycodo/scripts/upgrade_commands.sh
Fixed pigpio installation and removal bash script to reflect changes by pigpio author. New installation instructions found here:
http://abyz.me.uk/rpi/pigpio/download.html
Left code commented for comparison and feedback.
> saving upgrade_commands.sh changes

- mycodo/functions/backup_rsync.py
The current backup rsync function uses the standard ssh port 22 with no way to alter it. For security reasons, my backup server uses a nonstandard ssh port. So I added a bit to specify a different SSH port during rsync backup which defaults to port 22.
Alternatively, you can set the system-wide ssh port in _/etc/ssh/ssh_config_.
This works if every ssh connection you make uses the same port.
> Added nonstandard SSH port specification

- mycodo/inputs/mlx90393_circuitpython.py
Add Melexis MLX90393 3-axis magnetometer used in e.g. https://www.adafruit.com/product/4022. This implementation uses Adafruit's CircuitPython library for MLX90393.
> Add MLX90393 magnetic input

- mycodo/inputs/dps310_circuitpython.py
Add Infineon DPS310 pressure/temperature sensor used in e.g. https://www.adafruit.com/product/4494. This implementation uses Adafruit's CircuitPython library for DPS310.
> Add DPS310 pressure & temperature input

- databases/alembic/versions/0187ea22dc4b_add_camera_file_tracking_fields.py
- mycodo/databases/models/camera.py
- mycodo/devices/camera.py
- mycodo/mycodo_flask/routes_general.py
- mycodo/mycodo_flask/utils/utils_general.py
Resolves https://github.com/kizniche/Mycodo/issues/1086
This records the filename and timestamp of still and timelapse images in the database as they are generated and references that instead of scanning the filesystem for the newest of either. This should reduce load times for the camera administration page as well as dashboards with camera widgets showing recent images, especially when there are many files it would otherwise need to parse through.
`get_camera_image_info` still does a `listdir` on the filesystem for the array of timelapse images which I think could be optimized somehow (probably moved into its own method and called separately), but that's just a single call to list the directory contents whereas the checks for recent stills/timelapses would run a check for the mtime on …
> Optimize timelapse and still retrieval

- docs/Supported-Outputs.md
- mycodo/outputs/hs300.py
Support using the 6 outlet version of the Kasa wifi enabled power strip as Mycodo outputs.
Product info:
https://www.kasasmart.com/us/products/smart-plugs/kasa-smart-wi-fi-power-strip-hs300
This works fine as is, but it copies a lot of the code from the [KP303](https://github.com/kizniche/Mycodo/blob/master/mycodo/outputs/kp303.py) output. So they have a potential to drift in implementation. If you want to, I can pull out the common code somewhere and change the KP303 file to use that common code as well. We'd just need to decide where to put it as it doesn't seem like there is a place to put common code in the outputs namespace yet. Another option might be to make a single Kasa output, and make the number of outlets configurable. That might not be backwards compatible though.
> Adds support for the Kasa HS300 Wi-Fi Power Strip

- mycodo/inputs/bme680_circuitpython.py
Updated bme680 from 2.5.4 to 3.4.1
the older library no longer available on PyPI
> Bme680 lib fix

- mycodo/abstract_base_controller.py
Error occurs when trying to use an output using 'select_channel' from actions, in my case an HS300 power strip.
Error Logs
```
2022-03-12 22:03:07,184 - ERROR - mycodo.function_action.output_on_off_a52d7e4c - setup_custom_options_json() Unknown option type 'select_channel'
2022-03-12 22:03:07,238 - DEBUG - mycodo.function_action.output_on_off_a52d7e4c - Message: 2022-03-12 22:03:06
[Trigger 96d044dd-e2ee-4da6-a446-c085982d728c (Trigger: Timer (Duration))]
[Action a52d7e4c, Output: On/Off/Duration]: Turn output None CHNone (Power Strip) on for 5.0 seconds.
2022-03-12 22:03:07,239 - DEBUG - mycodo.trigger_action_a52d7e4c - Message: 2022-03-12 22:03:06
[Trigger 96d044dd-e2ee-4da6-a446-c085982d728c (Trigger: Timer (Duration))]
[Action a52d7e4c, Output: On/Off/Duration]: Turn output None …
```
> Fixed any output using 'select_channel' when used in actions

- docs/I2C-Multiplexers.md
I recently went through the setup for the TCA9548A multiplexer and ran into issues using the instructions provided, and the github repo linked for the TCA9545A driver no longer existed. The drivers are now a part of raspbian, so I added instructions on how to set that up instead of the outdated github repos!
> add instructions for multiplexers and remove outdated information

- mycodo/actions/mqtt_publish.py
- mycodo/actions/mqtt_publish_input.py
- mycodo/inputs/mqtt_paho.py
- mycodo/inputs/mqtt_paho_json.py
- mycodo/outputs/on_off_mqtt.py
- mycodo/outputs/value_mqtt.py
Add Websockets support to MQTT connections.
Or rather, make it possible to enable Websockets since `paho-mqtt` already supports them.
> Add Websocket support to MQTT connections

- mycodo/inputs/scd4x_circuitpython.py
Change argument passed to force_calibration method from float to int. The library is expecting an int as can be seen here: https://github.com/adafruit/Adafruit_CircuitPython_SCD4X/blob/a9ae07d8c30c45e7a36d5308bdaaa2887c3c7e31/adafruit_scd4x.py#L161
This fix restarts the device so that it automatically starts working without needing to deactivate and activate after force calibrating CO2.
NOTE: The adafruit library calls `sensor.stop_periodic_measurement()` at the begining of the function but never calls `sensor.start_periodic_measurement()` after it submits the calibration.
> Solution to Issue #1234

- mycodo/functions/display_generic_lcd_16x2_i2c.py
- mycodo/functions/display_generic_lcd_20x4_i2c.py
- mycodo/functions/display_grove_lcd_16x2_i2c.py
- mycodo/functions/display_ssd1306_oled_128x32_i2c.py
- mycodo/functions/display_ssd1306_oled_128x32_i2c_2lines.py
- mycodo/functions/display_ssd1306_oled_128x32_spi.py
- mycodo/functions/display_ssd1306_oled_128x32_spi_2lines.py
- mycodo/functions/display_ssd1306_oled_128x64_i2c.py
- mycodo/functions/display_ssd1306_oled_128x64_i2c_4lines.py
- mycodo/functions/display_ssd1306_oled_128x64_spi.py
- mycodo/functions/display_ssd1306_oled_128x64_spi_4lines.py
- mycodo/functions/display_ssd1309_oled_128x64_i2c.py
- mycodo/utils/influxdb_2.py
Hey, I spent several hours on tracking down a bug in the generic LCD functions. Because the `measure_max_age` value is listed as a `float`, the Flux query that gets created for Influx 2.x throws an error. It requires an `integer` value.
> Generic LCD Function Bug

- mycodo/inputs/ruuvitag.py
When using ruuvitag-sensor 1.2.0 and influxdb 2 on a 64bit platform, two conflicting versions of rx are needed. ruuvitag-sensor 2.0.0 seems to work fine.
> Update ruuvitag-sensor dependency

- mycodo/inputs/as7341_circuitpython.py
Add AS7341 multi-wavelength light sensor used in e.g. https://www.adafruit.com/product/4698. This implementation uses Adafruit's [CircuitPython library for AS7341](https://pypi.org/project/adafruit-circuitpython-as7341/).
I own this sensor and have tested it with Mycodo. Below is a graph showing captured data:
> Add AS7341 light spectrum input

- install/requirements.txt
When I installed Mycodo on a 32bit raspberry pi from both the latest release and master I see the following python dependency exception:
```
Collecting rpds-py>=0.7.1 (from jsonschema->Flask_RESTX==1.1.0->-r /home/pi/Mycodo/install/requirements.txt (line 16))
Downloading rpds_py-0.9.2.tar.gz (16 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Cargo, the Rust package manager, is not …
```
> Set python jsonschema version to 4.17.3 to avoid 4.18.x rust dependency

- mycodo/inputs/ahtx0_circuitpython.py
Newer AHT20s do not work, as they use a different calibration command as stated here : https://github.com/adafruit/Adafruit_CircuitPython_AHTx0/issues/17#issue-1920433739
To fix this problem the version should be bumped to the current one where they try the old and new calibration command. So far no other problems occured with this bugfix.
> Updated version of adafruit-circuitpython-ahtx0 library with bugfix

- mycodo/actions/output_ramp_pwm.py
`output_ramp_pwm` could attempt to divide by zero, crashing the action thread and leaving the output in an unexpected state.
`steps` was computed as `abs(start‑end)/increment` without validating that it was non‑zero.
* Derive `steps` safely and bail out if the ramp would be a NOP.
* Log a concise warning so users know why the ramp was skipped.
No other functional changes.
> Guard Ramp‑PWM against division‑by‑zero (start==end or increment==0)
